import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "./globals.css";

const lato = Lato({
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Bezt labs assignment",
  description: "Generated by anujgupta4155@gmail.com",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lato.className} antialiased`}>
        <div className="md:w-[375px] w-full h-full md:h-[812px] mx-auto ">
          {children}
        </div>
      </body>
    </html>
  );
}
